"""
SkillDocumentGenerator 单元测试
"""

import unittest
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from tests.test_base import KaelisTestBase


class TestSkillDocumentGenerator(KaelisTestBase):
    """测试技能文档生成器"""

    def setUp(self):
        super().setUp()
        from core.skill_generator import SkillDocumentGenerator
        self.SkillDocumentGenerator = SkillDocumentGenerator
        self.gen = SkillDocumentGenerator(output_dir=self.temp_dir)

    def test_generate_template(self):
        """使用模板生成"""
        record = {
            "task_type": "test_task",
            "best_params": {"x": 1},
            "best_result": {"score": 0.9},
            "best_confidence": 0.9,
            "iterations": []
        }
        path = self.gen.generate(record, skill_id="test_skill")
        self.assertIsNotNone(path)
        self.assertTrue(path.exists())

    def test_generate_with_llm(self):
        """使用 LLM 生成"""
        class MockLLM:
            def chat(self, prompt, temperature=0.3):
                return "# Mock Skill\n\nGenerated by mock LLM."
        gen = self.SkillDocumentGenerator(llm_client=MockLLM(), output_dir=self.temp_dir)
        record = {
            "task_type": "test_task",
            "best_params": {"x": 1},
            "best_result": {"score": 0.9},
            "best_confidence": 0.9,
            "iterations": []
        }
        path = gen.generate(record, skill_id="test_skill_llm")
        self.assertIsNotNone(path)

    def test_generate_llm_exception_fallback(self):
        """LLM 异常回退到模板"""
        class BadLLM:
            def chat(self, prompt, temperature=0.3):
                raise RuntimeError("boom")
        gen = self.SkillDocumentGenerator(llm_client=BadLLM(), output_dir=self.temp_dir)
        record = {
            "task_type": "test_task",
            "best_params": {"x": 1},
            "best_result": {"score": 0.9},
            "best_confidence": 0.9,
            "iterations": []
        }
        path = gen.generate(record, skill_id="test_skill_bad_llm")
        self.assertIsNotNone(path)

    def test_generate_exception(self):
        """生成异常返回 None"""
        path = self.gen.generate(None, skill_id="test")
        self.assertIsNone(path)

    def test_summarize_iterations_empty(self):
        """空迭代摘要"""
        result = self.gen._summarize_iterations([])
        self.assertEqual(result, "无迭代记录。")

    def test_summarize_iterations_many(self):
        """多轮迭代摘要"""
        iterations = [
            {"evaluation": {"confidence": 0.5, "passed": False}},
            {"evaluation": {"confidence": 0.6, "passed": False}},
            {"evaluation": {"confidence": 0.7, "passed": True}},
            {"evaluation": {"confidence": 0.8, "passed": True}},
            {"evaluation": {"confidence": 0.9, "passed": True}},
            {"evaluation": {"confidence": 0.95, "passed": True}},
        ]
        result = self.gen._summarize_iterations(iterations)
        self.assertIn("共 6 轮迭代", result)

    def test_get_skill_generator(self):
        """获取全局生成器"""
        from core.skill_generator import get_skill_generator
        gen1 = get_skill_generator()
        gen2 = get_skill_generator()
        self.assertIs(gen1, gen2)


if __name__ == "__main__":
    unittest.main()
