apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kaelis-hpa
  namespace: kaelis
  generated_at: '2026-04-13T01:39:17.494868'
  source: contracts/openapi.yaml
  annotations:
    kaelis.io/max-qps: '1000'
    kaelis.io/endpoints: '2'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kaelis-app
  minReplicas: 2
  maxReplicas: 7
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
