#!/usr/bin/env python3
"""
多 Agent 协作示例脚本
=====================
展示两个 Agent（研究员 + 分析师）通过 Kaelis 共享记忆空间协作。

前置条件:
    1. Kaelis 后端已启动: python launch.py
    2. 安装了 requests: pip install requests

运行:
    python examples/multi_agent_collab.py
"""

import sys
import requests
import json

# ==============================================================================
# Configuration
# ==============================================================================

BASE_URL = "http://localhost:5000/api/shared-memory"
SPACE_NAME = "Research Collab"
SPACE_DESC = "AI trends research workspace"

# Agent identities (X-Agent-ID header distinguishes them)
AGENT_RESEARCHER = "agent_researcher"
AGENT_ANALYST = "agent_analyst"


# ==============================================================================
# Helpers
# ==============================================================================

def health_check() -> bool:
    """检查 Kaelis 服务是否可用。"""
    try:
        resp = requests.get("http://localhost:5000/api/health", timeout=5)
        return resp.status_code == 200
    except requests.exceptions.ConnectionError:
        return False


def create_space(name: str, description: str = "") -> str:
    """创建共享空间，返回 space_id。如果已存在则复用。"""
    # 先尝试查找已有空间
    resp = requests.get(f"{BASE_URL}/spaces")
    if resp.status_code == 200:
        spaces = resp.json().get("data", [])
        for s in spaces:
            if s.get("name") == name:
                print(f"  [INFO] Reusing existing space: {s['space_id']}")
                return s["space_id"]

    # 创建新空间
    resp = requests.post(
        f"{BASE_URL}/spaces",
        json={"name": name, "description": description}
    )
    resp.raise_for_status()
    space_id = resp.json()["data"]["space_id"]
    print(f"  [OK] Created space: {space_id}")
    return space_id


def write_memory(
    space_id: str,
    key: str,
    value,
    tags: list = None,
    user_id: str = AGENT_RESEARCHER,
) -> dict:
    """Agent A: 写入记忆到共享空间。"""
    headers = {"X-Agent-ID": user_id}
    payload = {"key": key, "value": value}
    if tags:
        payload["tags"] = tags

    resp = requests.post(
        f"{BASE_URL}/spaces/{space_id}/memories",
        json=payload,
        headers=headers,
    )
    resp.raise_for_status()
    return resp.json()["data"]


def search_memory(space_id: str, query: str, user_id: str = AGENT_ANALYST) -> list:
    """Agent B: 搜索共享空间中的记忆。"""
    headers = {"X-Agent-ID": user_id}
    resp = requests.post(
        f"{BASE_URL}/spaces/{space_id}/search",
        json={"query": query, "top_k": 10},
        headers=headers,
    )
    resp.raise_for_status()
    return resp.json().get("data", [])


def generate_report(memories: list) -> str:
    """根据检索到的记忆生成 Markdown 报告。"""
    lines = [
        "# 🤖 AI Trends Report 2026",
        "",
        f"> Generated by **{AGENT_ANALYST}** | Data source: shared memory space",
        "",
        "---",
        "",
    ]

    for i, m in enumerate(memories, 1):
        content = m["value"] if isinstance(m["value"], str) else json.dumps(m["value"], ensure_ascii=False)
        tags = ", ".join(m.get("tags", []))
        author = m.get("metadata", {}).get("author", "unknown")
        version = m.get("version", 1)

        lines.append(f"## {i}. {m['key']}")
        lines.append(f"{content}")
        lines.append("")
        lines.append(f"- **Tags**: `{tags}`")
        lines.append(f"- **Author**: {author}")
        lines.append(f"- **Version**: v{version}")
        lines.append("")

    return "\n".join(lines)


# ==============================================================================
# Main Workflow
# ==============================================================================

def main():
    print("=" * 60)
    print("Kaelis Multi-Agent Collaboration Demo")
    print("=" * 60)

    # 1. Health check
    print("\n[1/5] Checking Kaelis service...")
    if not health_check():
        print("  [ERROR] Kaelis is not running at http://localhost:5000")
        print("  Please start it first: python launch.py")
        sys.exit(1)
    print("  [OK] Kaelis is online")

    # 2. Create shared space
    print(f"\n[2/5] Creating shared space '{SPACE_NAME}'...")
    space_id = create_space(SPACE_NAME, SPACE_DESC)

    # 3. Agent A writes findings
    print(f"\n[3/5] Agent A ({AGENT_RESEARCHER}) is collecting and writing findings...")
    findings = [
        {
            "key": "trend_2026_multi_agent",
            "value": "Multi-agent systems dominate enterprise AI adoption in 2026",
            "tags": ["AI", "trend", "2026"],
        },
        {
            "key": "trend_2026_memory_arch",
            "value": "Memory-centric agent architectures gain significant traction over RAG-only pipelines",
            "tags": ["AI", "memory", "architecture"],
        },
        {
            "key": "trend_2026_mcp",
            "value": "MCP (Model Context Protocol) becomes the standard for agent-tool interoperability",
            "tags": ["AI", "MCP", "protocol"],
        },
        {
            "key": "trend_2026_energy",
            "value": "Energy-aware strategy selection reduces inference costs by 30% in large agent fleets",
            "tags": ["AI", "energy", "cost"],
        },
    ]

    for f in findings:
        result = write_memory(
            space_id=space_id,
            key=f["key"],
            value=f["value"],
            tags=f.get("tags"),
            user_id=AGENT_RESEARCHER,
        )
        print(f"  [OK] {f['key']} → v{result['version']}")

    # 4. Agent B searches and generates report
    print(f"\n[4/5] Agent B ({AGENT_ANALYST}) is searching and generating report...")
    memories = search_memory(space_id, "AI trend", user_id=AGENT_ANALYST)
    print(f"  [OK] Found {len(memories)} relevant memories")

    report = generate_report(memories)

    # 5. Output
    print("\n[5/5] Final Report:")
    print("=" * 60)
    print(report)
    print("=" * 60)

    # Summary
    print(f"\n✅ Collaboration complete!")
    print(f"   Space ID : {space_id}")
    print(f"   Memories : {len(findings)} written by {AGENT_RESEARCHER}")
    print(f"   Retrieved: {len(memories)} by {AGENT_ANALYST}")
    print(f"\nYou can inspect this space in the Kaelis web UI:")
    print(f"   http://localhost:5000 → Memory → Shared Spaces")

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except requests.exceptions.HTTPError as e:
        print(f"\n[ERROR] HTTP {e.response.status_code}: {e.response.text}")
        sys.exit(1)
    except KeyboardInterrupt:
        print("\n\n[INTERRUPT] Demo stopped by user.")
        sys.exit(130)
