"""
AutoImmune-3: 测试骨架自动生成器
扫描 core/ 下新增的 .py 文件，检查 tests/ 下是否存在对应测试文件。
若不存在，自动生成包含 fixtures、基础测试、降级测试骨架的文件。
"""

import os
import re
from pathlib import Path
from typing import List, Set, Tuple


def find_untested_modules(core_dir: str = "core") -> List[Tuple[str, str]]:
    """找出有源码但无测试的模块，返回 [(module_path, test_file_name), ...]"""
    core_path = Path(core_dir)
    test_path = Path("tests")

    # 收集所有已有测试文件对应的模块名
    test_modules: Set[str] = set()
    if test_path.exists():
        for py_file in test_path.rglob("test_*.py"):
            # test_memory_manager.py -> memory_manager
            module_name = py_file.stem[5:]  # 去掉 "test_" 前缀
            test_modules.add(module_name)

    untested = []
    for py_file in core_path.rglob("*.py"):
        if py_file.name.startswith("__"):
            continue

        rel_path = py_file.relative_to(core_path)
        module_parts = list(rel_path.with_suffix("").parts)
        module_name = "_".join(module_parts)

        if module_name not in test_modules:
            test_file_name = f"test_{module_name}.py"
            untested.append((str(rel_path.with_suffix("")), test_file_name))

    return sorted(untested)


def generate_test_skeleton(module_path: str) -> str:
    """为模块生成测试骨架（避免 collection error）"""
    module_name = module_path.replace("\\", ".").replace("/", ".")
    safe_name = module_name.replace(".", "_")
    class_name = "".join(part.title() for part in safe_name.split("_"))

    skeleton = f'''"""
{module_name} module tests
Auto-generated by scripts/auto_gen_tests.py
"""
import pytest
import sys
from unittest.mock import patch, MagicMock


class Test{class_name}:
    """Main test class for {module_name}"""

    @pytest.fixture(scope="class")
    def module(self):
        """Lazy import to avoid collection errors."""
        return pytest.importorskip("core.{module_name}")

    def test_init_default(self, module):
        """Test default initialization"""
        # TODO: Add actual assertions
        assert module is not None

    def test_init_with_params(self, module):
        """Test initialization with custom parameters"""
        pass

    def test_basic_functionality(self, module):
        """Test core functionality"""
        pass

    def test_error_handling(self, module):
        """Test error handling paths"""
        pass


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''
    return skeleton


def main():
    import sys
    dry_run = "--apply" not in sys.argv

    print("=" * 60)
    print(" AutoImmune-3: Test Skeleton Auto-Generator")
    print("=" * 60)

    untested = find_untested_modules()

    if not untested:
        print("\n[OK] All core modules have corresponding test files.")
        return 0

    print(f"\n[WARN] Found {len(untested)} modules without tests:")
    for module_path, test_file in untested:
        print(f"  - core/{module_path}.py -> tests/{test_file}")

    if dry_run:
        print("\n[INFO] Dry-run mode. Run with --apply to generate test files.")
        print("\n[SAMPLE] Skeleton for first untested module:")
        print("-" * 40)
        print(generate_test_skeleton(untested[0][0]))
        print("-" * 40)
    else:
        generated = 0
        for module_path, test_file in untested:
            test_path = Path("tests") / test_file
            if test_path.exists():
                continue
            skeleton = generate_test_skeleton(module_path)
            test_path.write_text(skeleton, encoding="utf-8")
            generated += 1
            print(f"  [GEN] tests/{test_file}")
        print(f"\n[OK] Generated {generated} test skeletons.")

    return len(untested)


if __name__ == "__main__":
    import sys
    sys.exit(main())
