"""
Kaelis Developer Kit (KDK) — CLI Scaffolding Tool
=================================================
为开发者快速创建与 Kaelis 集成的项目模板。

用法:
    python scripts/kdk.py init my_project
    python scripts/kdk.py init my_project --template python
"""

import argparse
import logging
import sys
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")

# ============================================================================
# Templates
# ============================================================================

KAELIS_CONFIG = """# Kaelis Project Configuration
# 指向本地或远程 Kaelis 服务

service:
  # 本地开发模式
  endpoint: http://localhost:5000
  
  # 远程模式（生产环境）
  # endpoint: https://your-kaelis-instance.example.com

agent:
  # 项目专属 Agent ID
  id: {project_name}_agent
  
  # 默认记忆层
  default_memory_layer: L2
  
  # 自动将项目文档导入 Kaelis L3
  auto_ingest_docs: true

mcp:
  # 是否暴露项目自定义 Tools 到 Kaelis MCP Server
  expose_tools: true
  
  # 项目 Tools 目录
  tools_dir: ./kaelis_tools
"""

CI_YAML = """name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        run: |
          # 安装项目依赖
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f package.json ]; then npm ci; fi
      - name: Run tests
        run: |
          if [ -f pytest.ini ]; then pytest -q; fi
          if [ -f package.json ]; then npm test; fi
      - name: Run lint
        run: |
          if [ -f package.json ]; then npm run lint -- --max-warnings=20; fi
"""

PR_REVIEW_WORKFLOW = """name: Kaelis PR Review Agent

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize]

jobs:
  architecture-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Kaelis Review Agent
        run: |
          pip install PyJWT requests
          # 下载最新版 pr_review_agent.py（或从本地复制）
          curl -sL https://raw.githubusercontent.com/kaelis/kaelis/main/scripts/pr_review_agent.py -o scripts/pr_review_agent.py || true

      - name: Run PR Review Agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/pr_review_agent.py --rules-file pr_review_rules.yaml
"""

PR_RULES = """# Kaelis PR 审查规则配置
# 支持三种规则类型：regex、import_check、dependency_check

rules:
  # === Regex Rules ===
  - name: forbid_hardcoded_data_path
    type: regex
    pattern: 'Path\(["\']data/'
    severity: error
    message: "请使用注入的 db_dir 参数替代硬编码 data/ 路径（C1 契约）"

  - name: forbid_hardcoded_data_path_os
    type: regex
    pattern: 'os\.path\.join\([^)]*["\']data["\']'
    severity: error
    message: "请使用注入的 db_dir 参数替代硬编码 data/ 路径（C1 契约）"

  - name: require_circuit_breaker
    type: regex
    pattern: 'requests\.(get|post|put|delete)\('
    exclusion: 'CircuitBreaker|circuit_breaker|with_retry|resilience'
    severity: warning
    message: "外部 HTTP 调用应使用熔断器保护（参考 core/llm_client.py 的 CircuitBreaker）"

  - name: require_fallback_logic
    type: regex
    pattern: 'try:.*?(except\s*\w+Error:\s*raise|except\s*:\s*raise)'
    severity: warning
    message: "异常处理应有降级路径（返回默认值 / mock / 缓存），而非直接 re-raise（C4 契约）"

  # === Import Check Rules ===
  - name: api_layer_violation
    type: import_check
    source_pattern: '^api/routes/'
    forbidden_pattern: '^core/[a-z]+/[a-z]+'
    severity: error
    message: "api/routes/ 层不应直接导入 core/ 深层子模块，应通过 facade 或服务层"

  # === Dependency Check Rules ===
  - name: require_db_injectable
    type: dependency_check
    target_pattern: 'class.*Manager|def.*init.*self.*db'
    required_param: 'db_dir|db_path|persist_dir'
    severity: warning
    message: "数据库/文件管理类应支持 db_dir/db_path 参数注入（C1 契约）"
"""

README = """# {project_name}

Generated by Kaelis Developer Kit (KDK).

## 连接 Kaelis Dev Agent

1. 确保本地 Kaelis 服务运行：
   ```bash
   python prod_server.py
   ```

2. 配置 `.kaelis/config.yaml`：
   - 修改 `agent.id` 为你的项目专属 Agent ID
   - 调整 `service.endpoint` 指向你的 Kaelis 实例

3. 自动文档导入（可选）：
   ```bash
   python -c "from kaelis.ingest import ingest_docs; ingest_docs('.')"
   ```

## PR 审查

本项目已集成 Kaelis PR Review Agent：
- 规则文件：`pr_review_rules.yaml`
- 工作流：`.github/workflows/pr_review_agent.yml`
- 每次 PR 自动触发架构级审查

## 自定义规则

修改 `pr_review_rules.yaml` 添加你的项目特定规则：

```yaml
rules:
  - name: my_custom_rule
    type: regex
    pattern: 'some_pattern'
    severity: error
    message: "自定义错误信息"
```

## License

MIT
"""


# ============================================================================
# Scaffolder
# ============================================================================

def scaffold_project(project_name: str, target_dir: Optional[Path] = None) -> Path:
    """创建项目脚手架。"""
    if target_dir is None:
        target_dir = Path.cwd() / project_name

    if target_dir.exists():
        logger.error("Directory already exists: %s", target_dir)
        sys.exit(1)

    logger.info("Creating project: %s", project_name)

    # 目录结构
    dirs = [
        target_dir / ".kaelis",
        target_dir / ".github" / "workflows",
        target_dir / "scripts",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        logger.info("  Created: %s", d.relative_to(target_dir.parent if target_dir.parent != Path.cwd() else Path.cwd()))

    # 文件
    files = {
        target_dir / ".kaelis" / "config.yaml": KAELIS_CONFIG.format(project_name=project_name),
        target_dir / ".github" / "workflows" / "ci.yml": CI_YAML,
        target_dir / ".github" / "workflows" / "pr_review_agent.yml": PR_REVIEW_WORKFLOW,
        target_dir / "pr_review_rules.yaml": PR_RULES,
        target_dir / "README.md": README.format(project_name=project_name),
    }

    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
        logger.info("  Created: %s", path.name)

    # .gitignore
    gitignore = target_dir / ".gitignore"
    gitignore.write_text(".env\n__pycache__/\n*.pyc\nnode_modules/\n.kaelis/cache\n", encoding="utf-8")
    logger.info("  Created: .gitignore")

    logger.info("Project '%s' created successfully at %s", project_name, target_dir.resolve())
    return target_dir


# ============================================================================
# CLI
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        prog="kdk",
        description="Kaelis Developer Kit — Project scaffolding CLI",
    )
    subparsers = parser.add_subparsers(dest="command", help="Commands")

    # init
    init_parser = subparsers.add_parser("init", help="Create a new Kaelis-integrated project")
    init_parser.add_argument("project_name", help="Project directory name")
    init_parser.add_argument("--dir", type=Path, help="Target directory (default: ./<project_name>)")

    args = parser.parse_args()

    if args.command == "init":
        scaffold_project(args.project_name, target_dir=args.dir)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
